-- Base app schema

-- User
CREATE TYPE user_type AS ENUM ('admin', 'super');

CREATE TABLE admin_table (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  type user_type NOT NULL DEFAULT 'admin',

  -- Admin Credentials
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  pass_salt uuid NOT NULL DEFAULT gen_random_uuid(),
  token_salt uuid NOT NULL DEFAULT gen_random_uuid(),

  -- Timestamps
  cid BIGINT NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid BIGINT NOT NULL,
  mtime timestamp with time zone NOT NULL
);

CREATE TABLE user_info (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  -- User information
  firstname VARCHAR(255) NOT NULL,
  middlename VARCHAR(255) NOT NULL,
  lastname VARCHAR(255) NOT NULL,

  -- Timestamps
  cid BIGINT NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid BIGINT NOT NULL,
  mtime timestamp with time zone NOT NULL
);

CREATE TABLE user_contact_info (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  user_id BIGINT NOT NULL,
  email_address VARCHAR(255) NOT NULL UNIQUE,
  contact_number INT NOT NULL UNIQUE,

  -- Timestamps
  cid BIGINT NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid BIGINT NOT NULL,
  mtime timestamp with time zone NOT NULL
);

CREATE TABLE user_job (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  user_id BIGINT NOT NULL,
  occupation VARCHAR(255) NOT NULL,
  position VARCHAR(255) NOT NULL,

  -- Timestamps
  cid BIGINT NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid BIGINT NOT NULL,
  mtime timestamp with time zone NOT NULL
);

CREATE TABLE user_picture (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  user_id BIGINT NOT NULL,
  img_path VARCHAR(255) NOT NULL,

  -- Timestamps
  cid BIGINT NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid BIGINT NOT NULL,
  mtime timestamp with time zone NOT NULL
);

CREATE TABLE user_login (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  -- FK
  user_id BIGINT NOT NULL,

  -- Auth
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  pass_salt uuid NOT NULL DEFAULT gen_random_uuid(),
  token_salt uuid NOT NULL DEFAULT gen_random_uuid(),

  -- Timestamps
  cid BIGINT NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid BIGINT NOT NULL,
  mtime timestamp with time zone NOT NULL
);

CREATE TABLE building (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  user_id BIGINT NOT NULL,
  tower VARCHAR(255) NOT NULL,
  unit VARCHAR(255) NOT NULL,

  -- Timestamps
  cid BIGINT NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid BIGINT NOT NULL,
  mtime timestamp with time zone NOT NULL
);

CREATE TABLE refresh_token (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  refresh_token VARCHAR(255) NOT NULL,

  -- Timestamps
  cid BIGINT NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid BIGINT NOT NULL,
  mtime timestamp with time zone NOT NULL
)
